version: '3.8'

services:
  catoly-app:
    build: .
    container_name: catoly_app
    restart: always
    env_file: .env
    depends_on:
      - redis
      - vault
    ports:
      - "3000:4600"
    networks:
      - catoly-network

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - catoly-network

  vault:
    image: hashicorp/vault:latest
    container_name: vault_container
    restart: always
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_ADDR: http://0.0.0.0:8200
    command: server -dev
    networks:
      - app-network

networks:
  catoly-network:
    driver: bridge
